# -*- coding: utf-8 -*-
"""read_and_explore_json_file_ver3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmkudeJBGUMahLmiEWU7N6QqZbInGkdY
"""

import json
import numpy as np
import pandas as pd

def to_csv(path_in,path_out):
    with open(path_in, 'r') as file:
    # Parse JSON data
     data = json.load(file)
     # использование данных
     animals = data['images']
     list_1=[]
     list_2=[]
     list_3=[]
     list_4=[]
# перебор файлов
     for animal in animals:
        list_1.append(animal['file'])
        i=0
# перебор файлов для извлечения нужной категории и уверенности
     for animal in animals:
          a=0
          for i in range(len(animal['detections'])):
              kategoria=(animal['detections'][i]['category'])
              uverennost= (animal['detections'][i]['conf'])
              if int(kategoria)==1 and float(uverennost)>0.7:
                   a+=1
              i+=1
          if a:
                list_2.append(0), list_3.append(0), list_4.append(1)
          else: list_2.append(0), list_3.append(0), list_4.append(0)

     with_animals=pd.DataFrame({'filename':list_1, 'broken':list_2, 'empty':list_3, 'animal':list_4})
     with_animals.to_csv(path_out, sep=';', index=False, encoding='utf-8-sig')